source 'https://rubygems.org'

gem 'chef'
gem 'net-ssh-multi'
gem 'berkshelf'
gem 'chefspec'
gem 'foodcritic'
gem 'rake'
gem 'right_aws'
gem 'strainer'
gem 'guard'
gem 'guard-strainer'
gem 'pry'
gem 'pry-debugger'
gem 'pry-remote'
gem 'knife-solo_data_bag'
gem 'coveralls', require: false
gem 'test-kitchen'
gem 'kitchen-vagrant'